### ISSUE TITLE
How to iterate over commits to see how a project evolved over time?

### ISSUE THREAD

**Issue by pkollitsch** [sebastianbergmann/phploc#184]
Is there any advice available as to how I would go on to iterate over all available commits of a repo/branch to create an array of loc-data per commit? This would be interesting for info about the "evolution" of a project over time.

**Comment by muhammedeminakbulut** [comment]
I had a similar problem. I solved this by writing code that checks out (git checkout `hash`) each desired commit, measures, stores and then repeat the cycle. PHPLOC does not provide it. That is however really resource consuming and it takes a lot of time to calculate. I have tried it with the symfony/symfony repository but it takes ages because currently it has around 480+ tags. :) good luck.

**Comment by sebastianbergmann** [comment]
This functionality has been removed in PHPLOC 4.0.0.
