### ISSUE TITLE
Allow finder-facade 2

### ISSUE THREAD

**Issue by garak** [sebastianbergmann/phploc#201]
I need to install phpcpd 5 (dev, currently) and phploc, but I can't since the former is requiring finder-facade 2 (dev, too) while the latter is allowing only finder-facade 1

**Comment by sebastianbergmann** [comment]
Conflicts between (dependencies of) tools such as PHPCPD and PHPLOC can be avoided by using PHARs instead of installing them using Composer.

I do not understand understand why you "need" to install an unreleased development version of PHPCPD. Eventually, I will update this component's dependencies, and eventually there will be new releases. But all of this has very low priority for me.

**Comment by garak** [comment]
Well, I need it because it's currently the only one compatible with Symfony 5.
I'll try with phars, thanks for suggesion
